### ISSUE TITLE
[Bug] 1.3.0 Circular import

### ISSUE THREAD

**Issue by kamilkrzyskow** [GothicKit/ZenKit4Py#4]
Hi 👋,

https://github.com/GothicKit/ZenKit4Py/blob/be91b275b40047eed36ef2ade4729d318fd5d55e/src/zenkit/core/matrix.py#L7-L9

Should be
```py
from .quat import Quat
from .vector import Vec3f
from .vector import Vec4f
```

```py
Traceback (most recent call last):
  File "somedir\script.py", line 1, in <module>
    from zenkit import DaedalusScript
  File "somedir\venv\Lib\site-packages\zenkit\__init__.py", line 166, in <module>
    from zenkit._core import AxisAlignedBoundingBox
  File "somedir\venv\Lib\site-packages\zenkit\_core.py", line 35, in <module>
    from .core.color import Color
  File "somedir\venv\Lib\site-packages\zenkit\core\__init__.py", line 12, in <module>
    from .matrix import Mat3x3
  File "somedir\venv\Lib\site-packages\zenkit\core\matrix.py", line 7, in <module>
    from zenkit.core import Quat
ImportError: cannot import name 'Quat' from partially initialized module 'zenkit.core' (most likely due to a circular import) (somedir\venv\Lib\site-packages\zenkit\core\__init__.py)
```

**Comment by lmichaelis** [comment]
Hej there, thanks for the report! Yes indeed, looks like I missed that. Can you verify, that 80838356 works for you (`pip install -U git+https://github.com/GothicKit/ZenKit4Py.git@808383561408f45cadce77db25b8ef0132e5fa92`)?

**Comment by kamilkrzyskow** [comment]
It works 👍 
```py
$ python -c 'import zenkit; print(zenkit)'
<module 'zenkit' from 'somedir\\venv\\Lib\\site-packages\\zenkit\\__init__.py'>
$ pip freeze
zenkit @ git+https://github.com/GothicKit/ZenKit4Py.git@808383561408f45cadce77db25b8ef0132e5fa92
```

**Comment by kamilkrzyskow** [comment]
This was closed, but where is the 1.3.1 release?
Or do you wait for other issues to be reported first?

**Comment by lmichaelis** [comment]
Ah, not it wasn't published correctly appearantly. Should now be available: https://pypi.org/project/zenkit/1.3.0.post1/

**Comment by kamilkrzyskow** [comment]
Whoa, I think this is a first post-release I've seen in years, they're so rare in the projects I follow. However, personally I wouldn't use it as this is was a bug fix for a patch release 🤔 
- https://peps.python.org/pep-0440/#post-releases

Still, thanks a lot for the release 🤩 , I'll report anything new I find it, or create a PR :v:
